@host = http://localhost:3000
@Id = 66495afb9f675f2a866238b1
@devName = Ubisoft

### Test get all developers
GET {{host}}/developer

### Test get developer by id
GET {{host}}/developer/{{Id}}

### Test get developer by name
GET {{host}}/developer/name/{{devName}}

### Create developer
POST {{host}}/developer/
content-type: application/json

  {
    "Name": "Ubisoft",
    "Founded": "2020",
    "Headquarters": "Canada",
    "President": "John Denver",
    "Website": "ubisoft.com"
  }


### Update developer
PUT {{host}}/developer/{{Id}}
content-type: application/json

{
    "Name": "Microsoft",
    "Founded": "1998",
    "Headquarters": "USA",
    "President": "Bill Gates",
    "Website": "microsoft.com"
  }


### Delete developer by id
DELETE {{host}}/developer/{{Id}}