### LOCAL TEST

### Test locally Welcome
GET http://localhost:3000/

### Test locally get all reviews
GET http://localhost:3000/review

### Test locally get review by id
GET http://localhost:3000/review/6650254558df2d16e841b666

### Test locally get review by gameId
GET http://localhost:3000/review/game/664958029f675f2a865b4f1a




### Test locally get review by userId
GET http://localhost:3000/review/user/1919191919171

### Create Review
POST http://localhost:3000/review
content-type: application/json

{
    "UserId": 1919191919161,
    "Title": "A bad game",
    "Content": "I have never seen a game so bad",
    "Rating": 1,
    "Date": "5/24/2024",
    "Verified": "True"
  }


### Update review
PUT http://localhost:3000/review/665119fdb0bd4713f6f92c61
content-type: application/json

{
    "UserId": 1919191919161,
    "Title": "An average game",
    "Content": "I have never seen a game so average",
    "Rating": 5,
    "Date": "5/21/2024",
    "Verified": "True",
    "GameId": "664958029f675f2a865b4f1a"
  }


### Delete review by id
DELETE http://localhost:3000/review/665119fdb0bd4713f6f92c61

