
### Test locally Welcome
GET http://localhost:3000/

### Test locally get all developers
GET http://localhost:3000/developer

### Test locally get developer by id
GET http://localhost:3000/developer/66511f39c4fadbb7a2ca490b


### Test locally get developer by name
GET http://localhost:3000/developer/name/Ubisoft

### Create developer
POST http://localhost:3000/developer/
content-type: application/json

  {
    "Name": "Ubisoft2",
    "Founded": "2020",
    "Headquarters": "Canada",
    "President": "John Denver",
    "Website": "ubisoft.com"
  }


### Update developer
PUT http://localhost:3000/developer/66511f39c4fadbb7a2ca490b
content-type: application/json

{
    "Name": "Microsoft",
    "Founded": "1998",
    "Headquarters": "USA",
    "President": "Bill Gates",
    "Website": "microsoft.com"
  }


### Delete developer by id
DELETE http://localhost:3000/developer/66511fbb1fd8371a429ae8e6